import React from 'react';
import BatchMapping from '../../layouts/BatchMapping';
import pageMap from './pageMap';


/**
 * Batch Mapping Page
 * Generated by DevTools - Simple wrapper around BatchMapping
 * All data fetching, state management, and UI handled internally by BatchMapping
 */
const btchMapDetail = () => {
  return <BatchMapping pageMap={pageMap} />;
};

export default btchMapDetail;
