// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "btchMapDetail",
  "title": "Batch Mapping",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "btchMapDetail",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "section": "MAPPING",
    "layout": "MappingLayout",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": []
  },
  "formConfig": {
    "groups": []
  },
  "dmlConfig": {
    "fieldMappings": {},
    "operations": {
      "insert": {
        "excludeFields": []
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;