// Auto-generated by genPageMaps.js
export default {
  "id": "wrkrList",
  "title": "Workers",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "wrkrList"
  },
  "uiConfig": {
    "section": "reference",
    "icon": "Person",
    "color": "gray",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "wrkrID",
        "label": "wrkrID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "wrkrID",
            "label": "wrkrID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "wrkrID": "id",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "wrkrID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};