// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "prodBtchList",
  "title": "Product Batches",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "product_batches",
    "primaryKey": "prodBtchID",
    "listEvent": "prodBtchList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "inventory_2",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "prodBtchID",
        "label": "prodBtchID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "btchNbr",
        "label": "Batch Number",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "btchStart",
        "label": "Btch Start",
        "width": 120,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "btchLoc",
        "label": "Location",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "btchQty",
        "label": "Quantity",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "bestByDate",
        "label": "Best By Date",
        "width": 100,
        "type": "date",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodID",
        "label": "prodID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "prodBtchID",
            "label": "prodBtchID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "btchNbr",
            "label": "Batch Number",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "btchStart",
            "label": "Btch Start",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "prodID",
            "label": "prodID",
            "type": "select",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctID",
            "label": "Account",
            "type": "select",
            "required": false,
            "hidden": false,
            "widget": "selAcct"
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "btchLoc",
            "label": "Location",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "btchQty",
            "label": "Quantity",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "measID",
            "label": "Measure",
            "type": "select",
            "required": true,
            "hidden": false,
            "widget": "selMeas"
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "bestByDate",
            "label": "Best By Date",
            "type": "date",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "comments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "prodBtchID": "id",
      "btchNbr": "batch_number",
      "btchStart": "'%Y-%m-%d')",
      "btchLoc": "location",
      "btchQty": "batch_quantity",
      "measID": "global_measure_unit_id",
      "bestByDate": "'%Y-%m-%d')",
      "comments": "comments",
      "prodID": "product_id",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "prodBtchID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;