graph TD
  brndList[brndList]
  brndList_comp[brndList Component]
  brndList_map[brndList PageMap]
  brndList_comp --> brndList_map
  brndList_map --> brndList
  brndList --> brands_db[(brands)]
  style brndList fill:#e1f5fe
  btchMapping[btchMapping]
  btchMapping_comp[btchMapping Component]
  btchMapping_map[btchMapping PageMap]
  btchMapping_comp --> btchMapping_map
  btchMapping_map --> btchMapping
  ingrBtchList[ingrBtchList]
  ingrBtchList_comp[ingrBtchList Component]
  ingrBtchList_map[ingrBtchList PageMap]
  ingrBtchList_comp --> ingrBtchList_map
  ingrBtchList_map --> ingrBtchList
  ingrBtchList --> ingredient_batches_db[(ingredient_batches)]
  style ingrBtchList fill:#e1f5fe
  ingrList[ingrList]
  ingrList_comp[ingrList Component]
  ingrList_map[ingrList PageMap]
  ingrList_comp --> ingrList_map
  ingrList_map --> ingrList
  ingrList --> ingredients_db[(ingredients)]
  style ingrList fill:#e1f5fe
  ingrTypeList[ingrTypeList]
  ingrTypeList_comp[ingrTypeList Component]
  ingrTypeList_map[ingrTypeList PageMap]
  ingrTypeList_comp --> ingrTypeList_map
  ingrTypeList_map --> ingrTypeList
  ingrTypeList --> ingredient_types_db[(ingredient_types)]
  style ingrTypeList fill:#e1f5fe
  measList[measList]
  measList_comp[measList Component]
  measList_map[measList PageMap]
  measList_comp --> measList_map
  measList_map --> measList
  measList --> measures_db[(measures)]
  style measList fill:#e1f5fe
  prodBtchList[prodBtchList]
  prodBtchList_comp[prodBtchList Component]
  prodBtchList_map[prodBtchList PageMap]
  prodBtchList_comp --> prodBtchList_map
  prodBtchList_map --> prodBtchList
  prodBtchList --> product_batches_db[(product_batches)]
  style prodBtchList fill:#e1f5fe
  prodList[prodList]
  prodList_comp[prodList Component]
  prodList_map[prodList PageMap]
  prodList_comp --> prodList_map
  prodList_map --> prodList
  prodList --> products_db[(products)]
  style prodList fill:#e1f5fe
  prodTypeList[prodTypeList]
  prodTypeList_comp[prodTypeList Component]
  prodTypeList_map[prodTypeList PageMap]
  prodTypeList_comp --> prodTypeList_map
  prodTypeList_map --> prodTypeList
  prodTypeList --> product_types_db[(product_types)]
  style prodTypeList fill:#e1f5fe
  rcpeList[rcpeList]
  rcpeList_comp[rcpeList Component]
  rcpeList_map[rcpeList PageMap]
  rcpeList_comp --> rcpeList_map
  rcpeList_map --> rcpeList
  rcpeList --> product_recipes_db[(product_recipes)]
  taskList[taskList]
  taskList_comp[taskList Component]
  taskList_map[taskList PageMap]
  taskList_comp --> taskList_map
  taskList_map --> taskList
  taskList --> tasks_db[(tasks)]
  style taskList fill:#e1f5fe
  userLogin[userLogin]
  userLogin_comp[userLogin Component]
  userLogin_map[userLogin PageMap]
  userLogin_comp --> userLogin_map
  userLogin_map --> userLogin
  userLogin --> users_db[(users)]
  vndrList[vndrList]
  vndrList_comp[vndrList Component]
  vndrList_map[vndrList PageMap]
  vndrList_comp --> vndrList_map
  vndrList_map --> vndrList
  vndrList --> vendors_db[(vendors)]
  style vndrList fill:#e1f5fe
  wrkrList[wrkrList]
  wrkrList_comp[wrkrList Component]
  wrkrList_map[wrkrList PageMap]
  wrkrList_comp --> wrkrList_map
  wrkrList_map --> wrkrList
  wrkrList --> workers_db[(workers)]
  style wrkrList fill:#e1f5fe
  userAcctList[userAcctList]
  undefined_comp[undefined Component]
  undefined_map[undefined PageMap]
  undefined_comp --> undefined_map
  undefined_map --> userAcctList
  archDashboard[archDashboard]
  undefined_comp[undefined Component]
  undefined_map[undefined PageMap]
  undefined_comp --> undefined_map
  undefined_map --> archDashboard
