// Auto-generated by genPageMaps.js
export default {
  "id": "userList",
  "title": "Users",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "userList"
  },
  "uiConfig": {
    "section": "admin",
    "icon": "Group",
    "color": "indigo",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "userID",
        "label": "userID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "lastName",
        "label": "Last Name",
        "width": 150,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "firstName",
        "label": "First Name",
        "width": 150,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "userEmail",
        "label": "Email",
        "width": 150,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "password",
        "label": "Password",
        "width": 150,
        "type": "hidden",
        "editable": true,
        "hidden": false
      },
      {
        "field": "roleID",
        "label": "Role",
        "width": 150,
        "type": "select",
        "editable": true,
        "hidden": false
      },
      {
        "field": "dfltAcctID",
        "label": "Default Account",
        "width": 150,
        "type": "select",
        "editable": true,
        "hidden": false
      },
      {
        "field": "lastLogin",
        "label": "Last Login",
        "width": 150,
        "type": "date",
        "editable": true,
        "hidden": false
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "userID",
            "label": "userID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "lastName",
            "label": "Last Name",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "firstName",
            "label": "First Name",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "userEmail",
            "label": "Email",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "password",
            "label": "Password",
            "type": "hidden",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "roleID",
            "label": "Role",
            "type": "select",
            "required": false,
            "hidden": false,
            "selList": "userRoleList"
          },
          {
            "field": "dfltAcctID",
            "label": "Default Account",
            "type": "select",
            "required": false,
            "hidden": false,
            "selList": "acctList"
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "lastLogin",
            "label": "Last Login",
            "type": "date",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "userID": "userID",
      "lastName": "lastName",
      "firstName": "firstName",
      "userEmail": "userEmail",
      "password": "password",
      "roleID": "roleID",
      "dfltAcctID": "dfltAcctID",
      "lastLogin": "lastLogin"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "userID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};