// Auto-generated by genPageMaps.js
export default {
  "id": "brndList",
  "title": "Brands",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "brndList"
  },
  "uiConfig": {
    "section": "reference",
    "icon": "Branding",
    "color": "gray",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "brndID",
        "label": "brndID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "brndName",
        "label": "Brand Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "brndID",
            "label": "brndID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "brndName",
            "label": "Brand Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "brndComments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "brndURL",
            "label": "Website",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "brndID": "brndID",
      "brndName": "brndName",
      "brndComments": "brndComments",
      "brndURL": "brndURL",
      "acctID": "acctID"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "brndID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};