import React from 'react';
import RecipeLayout from '../../layouts/RecipeLayout';
import pageMap from './pageMap';


/**
 * Product Recipes Page
 * Generated by DevTools - Simple wrapper around RecipeLayout
 * All data fetching, state management, and UI handled internally by RecipeLayout
 */
const rcpeList = () => {
  return <RecipeLayout pageMap={pageMap} />;
};

export default rcpeList;
