// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "rcpeList",
  "title": "Product Recipes",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "product_recipes",
    "primaryKey": "rcpeID",
    "listEvent": "rcpeList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "section": "PRODUCTS",
    "layout": "RecipeLayout",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "rcpeID",
        "label": "rcpeID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrOrdr",
        "label": "Order",
        "width": "80",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrName",
        "label": "Ingredient Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "qtyMeas",
        "label": "Quantity & Measure",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodID",
        "label": "prodID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrTypeSel",
        "label": "Ingredient Type",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrSel",
        "label": "Ingredient",
        "width": "180",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "measID",
        "label": "Measure",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "Qty",
        "label": "Quantity",
        "width": "100",
        "type": "text",
        "editable": true,
        "hidden": false
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "rcpeID",
            "label": "rcpeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrOrdr",
            "label": "Order",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "ingrName",
            "label": "Ingredient Name",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "prodID",
            "label": "prodID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "qtyMeas",
            "label": "Quantity & Measure",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "measID",
            "label": "Measure",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "Qty",
            "label": "Quantity",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "ingrTypeSel",
            "label": "Ingredient Type",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "ingrSel",
            "label": "Ingredient",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "Comments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "rcpeID": "prd_rcpe_id",
      "ingrOrdr": "ingr_ordr",
      "ingrName": "ingr_name",
      "qtyMeas": "ingr_qty_meas",
      "prodID": "prd_id",
      "ingrTypeSel": "ingr_type_id",
      "ingrSel": "ingr_id",
      "measID": "ingr_meas_id",
      "Qty": "ingr_qty",
      "Comments": "prd_ingr_desc"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "rcpeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;