CREATE TABLE IF NOT EXISTS _old_eventComp_xref (
  id int NOT NULL AUTO_INCREMENT,
    pageID int DEFAULT NULL,
    comp_name varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    title varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    parent_id int DEFAULT NULL,
    comp_type varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    composite_id int DEFAULT NULL COMMENT 'References eventComposite.id - which template/recipe to use',
    posOrder varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '00,00,00,left',
    props text COLLATE utf8mb4_general_ci,
    triggers text COLLATE utf8mb4_general_ci,
    description varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    style text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'Paul',
    updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    deleted_at timestamp NULL DEFAULT NULL,
    deleted_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    active tinyint(1) GENERATED ALWAYS AS ((case when (deleted_at is null) then 1 else 0 end)) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY usi_pageID_compName (pageID,comp_name),
    KEY eventComp_xref_comp_type_FK (comp_type),
    KEY idx_composite_id (composite_id),
    CONSTRAINT eventComp_xref_comp_type_FK FOREIGN KEY (comp_type) REFERENCES _old_eventType (name) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_eventComp_xref_composite FOREIGN KEY (composite_id) REFERENCES composites (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
