CREATE TABLE IF NOT EXISTS composites (
  id int NOT NULL AUTO_INCREMENT,
    category varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
    name varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
    renderer varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL,
    title varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
    components text COLLATE utf8mb4_general_ci,
    layout text COLLATE utf8mb4_general_ci,
    dependencies text COLLATE utf8mb4_general_ci,
    props json DEFAULT NULL,
    eventSQL json DEFAULT NULL,
    triggers json DEFAULT NULL,
    style text COLLATE utf8mb4_general_ci,
    purpose text COLLATE utf8mb4_general_ci,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'Paul',
    updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    deleted_at timestamp NULL DEFAULT NULL,
    deleted_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    active tinyint(1) GENERATED ALWAYS AS ((case when (deleted_at is null) then 1 else 0 end)) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY usi_composite_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
