CREATE TABLE IF NOT EXISTS pageComponents (
  id int NOT NULL AUTO_INCREMENT,
    pageID int NOT NULL,
    comp_name varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Unique name on this page',
    composite_id int NOT NULL COMMENT 'References eventComposite.id',
    parent_id int DEFAULT NULL COMMENT 'References pageComponents.id (self)',
    posOrder varchar(25) COLLATE utf8mb4_general_ci DEFAULT '00,00,00,left' COMMENT 'Row, column, order, alignment',
    title varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Display title override',
    style text COLLATE utf8mb4_general_ci COMMENT 'Component-specific style overrides',
    description varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(50) COLLATE utf8mb4_general_ci DEFAULT 'system',
    updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
    deleted_at timestamp NULL DEFAULT NULL,
    deleted_by varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
    active tinyint(1) GENERATED ALWAYS AS ((case when (deleted_at is null) then 1 else 0 end)) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY usi_page_component (pageID,comp_name),
    KEY idx_pageID (pageID),
    KEY idx_composite_id (composite_id),
    KEY idx_parent_id (parent_id),
    KEY idx_active (active),
    CONSTRAINT fk_pageComponents_composite FOREIGN KEY (composite_id) REFERENCES composites (id),
    CONSTRAINT fk_pageComponents_page FOREIGN KEY (pageID) REFERENCES page_registry (id),
    CONSTRAINT fk_pageComponents_parent FOREIGN KEY (parent_id) REFERENCES pageComponents (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Component instances on pages - replaces eventComp_xref';
