CREATE TABLE IF NOT EXISTS plan_impacts (
  id int unsigned NOT NULL AUTO_INCREMENT,
    plan_id int unsigned NOT NULL,
    file_path varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
    phase varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'idea',
    change_type varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
    status varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending',
    description text COLLATE utf8mb4_general_ci,
    batch_id varchar(50) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (concat(created_by,_utf8mb4'-',date_format(created_at,_utf8mb4'%Y-%m-%d %H%i'))) STORED,
    affected_apps json DEFAULT NULL COMMENT 'Array of apps affected by the change',
    auto_generated tinyint(1) NOT NULL DEFAULT '0' COMMENT 'True if auto-generated impact',
    cross_app_analysis json DEFAULT NULL COMMENT 'Cross-app dependency analysis results',
    fileName varchar(255) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (substring_index(file_path,_utf8mb4'/',-(1))) STORED,
    fileFolder varchar(255) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (substr(file_path,1,((length(file_path) - length(substring_index(file_path,_utf8mb4'/',-(1)))) - 1))) STORED,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    deleted_at timestamp NULL DEFAULT NULL,
    deleted_by varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_plan_impacts_plan_id (plan_id),
    KEY idx_plan_impacts_file (file_path),
    KEY Idx_plan_impacts_phase (phase),
    KEY idx_plan_impacts_folder (fileFolder),
    KEY idx_plan_impacts_batch_id (batch_id) USING BTREE,
    KEY idx_plan_impacts_auto_generated (auto_generated) USING BTREE,
    CONSTRAINT plan_impacts_ibfk_1 FOREIGN KEY (plan_id) REFERENCES plans (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
