import React from 'react';
import { CrudLayout } from '@whatsfresh/shared-imports';
import pageMap from './pageMap';


/**
 * Recipes Page
 * Generated by DevTools - Simple wrapper around CrudLayout
 * All data fetching, state management, and UI handled internally by CrudLayout
 */
const rcpeListPage = () => {
  return <CrudLayout pageMap={pageMap} />;
};

export default rcpeListPage;
