/**
 * Type definitions for the Impact Tracking system
 */

/**
 * File Change Event - represents a file system change
 * @typedef {Object} FileChangeEvent
 * @property {'CREATE'|'MODIFY'|'DELETE'} type - Type of file change
 * @property {string} filePath - Absolute path to the changed file
 * @property {Date} timestamp - When the change occurred
 * @property {number} [size] - File size after change
 */

/**
 * Impact Record - represents an impact to be tracked
 * @typedef {Object} ImpactRecord
 * @property {number} [planId] - Associated plan ID (added by context analyzer)
 * @property {string} filePath - Relative path from monorepo root
 * @property {'CREATE'|'MODIFY'|'DELETE'} changeType - Type of change
 * @property {string[]} affectedApps - List of affected application names
 * @property {string} description - Human-readable description
 * @property {Date} timestamp - When the change occurred
 * @property {string} userId - User who made the change
 * @property {string} [batchId] - Batch ID for grouped changes
 * @property {boolean} autoGenerated - True for automatically tracked impacts
 * @property {Object} [crossAppAnalysis] - Detailed cross-app impact analysis
 */

/**
 * Plan Context - information about the current plan being worked on
 * @typedef {Object} PlanContext
 * @property {number} planId - The plan ID
 * @property {string} planName - Human-readable plan name
 * @property {'contextStore'|'fileSystem'|'guidance'|'manual'} source - How the context was determined
 * @property {number} confidence - Confidence score (0-1) for the plan association
 */

/**
 * App Impact - detailed impact analysis for a specific app
 * @typedef {Object} AppImpact
 * @property {string} appName - Name of the affected app
 * @property {'direct'|'dependency'|'potential'} impactType - Type of impact
 * @property {'low'|'medium'|'high'} severity - Severity of the impact
 * @property {string} description - Description of the impact
 */

/**
 * Impact Batch - group of related impacts
 * @typedef {Object} ImpactBatch
 * @property {string} batchId - Unique batch identifier
 * @property {string} batchDescription - Description for the entire batch
 * @property {ImpactRecord[]} impacts - Individual impact records in the batch
 * @property {Date} createdAt - When the batch was created
 */

/**
 * Configuration for Impact Processor
 * @typedef {Object} ImpactProcessorConfig
 * @property {string} monorepoRoot - Root directory of the monorepo
 * @property {string[]} excludePatterns - Glob patterns for files to exclude
 * @property {string[]} trackableExtensions - File extensions to track
 * @property {number} debounceMs - Debounce time for rapid changes
 */

export const CHANGE_TYPES = {
  CREATE: "CREATE",
  MODIFY: "MODIFY",
  DELETE: "DELETE",
};

export const IMPACT_TYPES = {
  DIRECT: "direct",
  DEPENDENCY: "dependency",
  POTENTIAL: "potential",
};

export const SEVERITY_LEVELS = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
};

export const PLAN_CONTEXT_SOURCES = {
  CONTEXT_STORE: "contextStore",
  FILE_SYSTEM: "fileSystem",
  GUIDANCE: "guidance",
  MANUAL: "manual",
};

export const APP_NAMES = {
  CLIENT: "wf-client",
  ADMIN: "wf-admin",
  PLAN_MANAGEMENT: "wf-plan-management",
  SERVER: "wf-server",
};
