/**
 * Generated Routes Configuration for client
 * Auto-generated by devtools - DO NOT EDIT MANUALLY
 */

export const ROUTES = {
  "LOGIN": {
    "path": "/userLogin",
    "component": "0-Auth/01-Login/index.js",
    "layout": "AuthLayout",
    "title": "Login",
    "icon": "Login",
    "section": "auth",
    "eventType": "userLogin",
    "params": [
      ":userEmail",
      ":enteredPassword"
    ],
    "category": "page:Login"
  }
};

export const SECTIONS = {
  "auth": {
    "name": "auth",
    "order": 999,
    "items": [
      {
        "routeKey": "LOGIN",
        "title": "Login",
        "icon": "Login",
        "order": 999,
        "color": "blue"
      }
    ]
  }
};

export function getNavSections() {
  return Object.values(SECTIONS).sort((a, b) => (a.order || 999) - (b.order || 999));
}

export function getRoute(routeKey) {
  return ROUTES[routeKey];
}

export function resolveRoute(eventType) {
  return Object.values(ROUTES).find(route => route.eventType === eventType);
}

// Generated on: 2025-07-04T19:56:25.179Z
