/**
 * Navigation Generation Utility
 * Generates app-specific navigation based on routes
 */

import { generateRoutes } from './routeGenerator.js';

/**
 * Generate navigation configuration for an app
 * @param {string} appType - 'client' or 'admin'
 * @returns {string} Generated navigation file content
 */
export function generateNavigationFile(appType = 'client') {
    const { sections } = generateRoutes(appType);

    return `/**
 * Generated Navigation Configuration for ${appType}
 * Auto-generated by devtools - DO NOT EDIT MANUALLY
 */

import { getNavSections } from './routes.js';

/**
 * Navigation configuration for the application sidebar
 * Based on the section structure defined in routes.js
 */
export const navigationConfig = (acctID) => {
  // Get sections with their items from routes
  const sections = getNavSections();
  const result = [];
  
  sections.forEach(section => {
    const sectionConfig = {
      name: section.name,
      items: section.items.map(item => ({
        name: item.title,
        icon: item.icon,
        route: item.routeKey,
        color: item.color || 'gray'
      }))
    };
    
    result.push(sectionConfig);
  });
  
  return result;
};

// Generated on: ${new Date().toISOString()}
`;
}
