// Auto-generated by genPageMaps.js
export default {
  "id": "taskList",
  "title": "Tasks",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "tasks",
    "primaryKey": "taskID",
    "listEvent": "taskList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "task_alt",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "taskID",
        "label": "taskID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "taskOrder",
        "label": "Order",
        "width": "80",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodTypeID",
        "label": "prodTypeID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "taskID",
            "label": "taskID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "taskDesc",
            "label": "Description",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "taskOrder",
            "label": "Order",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "prodTypeID",
            "label": "prodTypeID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "taskID": "id",
      "taskDesc": "description",
      "taskOrder": "ordr",
      "prodTypeID": "product_type_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "taskID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};