// Auto-generated by genPageMaps.js
const ingrTypeListPageMap = {
  "id": "ingrTypeList",
  "title": "Ingredient Types",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "ingrTypeList"
  },
  "uiConfig": {
    "section": "ingredients",
    "icon": "Category",
    "color": "pink",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrTypeID",
        "label": "ingrTypeID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrTypeID",
            "label": "ingrTypeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrTypeDesc",
            "label": "Description",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrTypeID": "id",
      "ingrTypeDesc": "description",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrTypeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default ingrTypeListPageMap;