// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "ingrTypeList",
  "title": "Ingredient Types",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredient_types",
    "primaryKey": "ingrTypeID",
    "listEvent": "ingrTypeList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "category",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrTypeID",
        "label": "ingrTypeID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrTypeName",
        "label": "Type Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrTypeID",
            "label": "ingrTypeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrTypeName",
            "label": "Type Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "ingrTypeDesc",
            "label": "Description",
            "type": "multiLine",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrTypeID": "id",
      "ingrTypeName": "name",
      "ingrTypeDesc": "description",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrTypeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;