/**
 * Preview Routes Manifest
 * AUTO-GENERATED by genPageConfig - DO NOT EDIT MANUALLY
 *
 * This file is automatically updated when pages are generated via genPageConfig.
 * Preview routes allow testing database-generated pages before deployment.
 */

export const PREVIEW_ROUTES = [
  {
    "path": "/preview/wf-login/loginPage",
    "component": "preview/wf-login/loginPage",
    "title": "loginPage",
    "appName": "wf-login",
    "pageName": "loginPage",
    "generated": "2025-10-01T21:04:06.227Z"
  }
];
