graph TD

    studio["studio<br/>ctgry: [page]"]
    pageConfigHier["pageConfigHier<br/>ctgry: [serverquery]"]
    studio --> pageConfigHier
    columnSidebar["columnSidebar<br/>ctgry: [sidebar]"]
    studio --> columnSidebar
    newComponent["newComponent<br/>ctgry: [column]"]
    studio --> newComponent
    tabsWorkArea["tabsWorkArea<br/>ctgry: [tabs]"]
    studio --> tabsWorkArea
    selectApp["selectApp<br/>ctgry: [select]"]
    columnSidebar --> selectApp
    selectPage["selectPage<br/>ctgry: [select]"]
    columnSidebar --> selectPage
    btnGenPageConfig["btnGenPageConfig<br/>ctgry: [button]"]
    columnSidebar --> btnGenPageConfig
    appList["appList<br/>ctgry: [serverquery]"]
    selectApp --> appList
    pageList["pageList<br/>ctgry: [serverquery]"]
    selectPage --> pageList

    %% Click handlers for Studio integration
    click studio href "javascript:window.selectEventTypeTab(24)"
    click pageConfigHier href "javascript:window.selectEventTypeTab(39)"
    click columnSidebar href "javascript:window.selectEventTypeTab(31)"
    click newComponent href "javascript:window.selectEventTypeTab(32)"
    click tabsWorkArea href "javascript:window.selectEventTypeTab(33)"
    click selectApp href "javascript:window.selectEventTypeTab(35)"
    click selectPage href "javascript:window.selectEventTypeTab(36)"
    click btnGenPageConfig href "javascript:window.selectEventTypeTab(37)"
    click appList href "javascript:window.selectEventTypeTab(34)"
    click pageList href "javascript:window.selectEventTypeTab(38)"