// Auto-generated by genPageMaps.js
export default {
  "id": "ingrBtchList",
  "title": "Ingredient Batches",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "ingrBtchList"
  },
  "uiConfig": {
    "section": "ingredients",
    "icon": "Inventory",
    "color": "pink",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrBtchID",
        "label": "Ingr Btch I D",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "btchNbr",
        "label": "Batch Number",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "purchDate",
        "label": "Purch Date",
        "width": 100,
        "type": "date",
        "editable": true,
        "hidden": false
      },
      {
        "field": "unitQty",
        "label": "Unit Qty",
        "width": "80",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "unitPrice",
        "label": "Unit Price",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "purchQty",
        "label": "Purchase Qty",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "lotNbr",
        "label": "Lot Number",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "bestByDate",
        "label": "Best By Date",
        "width": 100,
        "type": "date",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrID",
        "label": "Ingredient",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      },
      {
        "field": "DECIMAL",
        "label": "D E C I M A L",
        "width": 120,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "purch_dtl",
        "label": "Purch_dtl",
        "width": 120,
        "type": "text",
        "editable": true,
        "hidden": false
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrBtchID",
            "label": "Ingr Btch I D",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "btchNbr",
            "label": "Batch Number",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "vndrID",
            "label": "Vendor",
            "type": "select",
            "required": true,
            "hidden": false,
            "widget": "selVndr"
          },
          {
            "field": "ingrID",
            "label": "Ingredient",
            "type": "select",
            "required": false,
            "hidden": true
          },
          {
            "field": "DECIMAL",
            "label": "D E C I M A L",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "purch_dtl",
            "label": "Purch_dtl",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "Account",
            "type": "select",
            "required": false,
            "hidden": false,
            "widget": "selAcct"
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "brndID",
            "label": "Brand",
            "type": "select",
            "required": false,
            "hidden": false,
            "widget": "selBrnd"
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "unitQty",
            "label": "Unit Qty",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "unitPrice",
            "label": "Unit Price",
            "type": "decimal",
            "required": false,
            "hidden": false
          },
          {
            "field": "purchQty",
            "label": "Purchase Qty",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "measID",
            "label": "Measure",
            "type": "select",
            "required": true,
            "hidden": false,
            "widget": "selMeas"
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "purchDate",
            "label": "Purch Date",
            "type": "date",
            "required": false,
            "hidden": false
          },
          {
            "field": "lotNbr",
            "label": "Lot Number",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "bestByDate",
            "label": "Best By Date",
            "type": "date",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "comments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrBtchID": "ingrBtchID",
      "btchNbr": "btchNbr",
      "vndrID": "vndrID",
      "brndID": "brndID",
      "purchDate": "purchDate",
      "unitQty": "unitQty",
      "unitPrice": "unitPrice",
      "purchQty": "purchQty",
      "measID": "measID",
      "lotNbr": "lotNbr",
      "bestByDate": "bestByDate",
      "comments": "comments",
      "ingrID": "ingrID",
      "DECIMAL": "DECIMAL",
      "purch_dtl": "purch_dtl",
      "acctID": "acctID"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrBtchID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};