// Auto-generated by genPageMaps.js
export default {
  "id": "measList",
  "title": "Measures",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "measList"
  },
  "uiConfig": {
    "section": "reference",
    "icon": "Scale",
    "color": "gray",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "measID",
        "label": "measID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "name",
        "label": "Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "abbrev",
        "label": "Abbreviation",
        "width": "100",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "measID",
            "label": "measID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "name",
            "label": "Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "abbrev",
            "label": "Abbreviation",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "measID": "measID",
      "name": "name",
      "abbrev": "abbrev",
      "acctID": "acctID"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "measID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};