// Auto-generated by genPageMaps.js
export default {
  "id": "ingrList",
  "title": "Ingredients",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredients",
    "primaryKey": "ingrID",
    "parentIdField": "ingrTypeID",
    "childEntity": "ingrBtchList",
    "childIdField": "ingrID",
    "listEvent": "ingrList"
  },
  "uiConfig": {
    "section": "ingredients",
    "icon": "ListAlt",
    "color": "pink",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrID",
        "label": "ingrID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrName",
        "label": "Ingredient Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrCode",
        "label": "Code",
        "width": "100",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrGrmsPerOz",
        "label": "Grams/Oz",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrTypeID",
        "label": "ingrTypeID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrID",
            "label": "ingrID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrName",
            "label": "Ingredient Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "ingrCode",
            "label": "Code",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "ingrTypeID",
            "label": "ingrTypeID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "measID",
            "label": "Default Measure",
            "type": "select",
            "required": false,
            "hidden": false,
            "selList": "measList"
          },
          {
            "field": "vndrID",
            "label": "Default Vendor",
            "type": "select",
            "required": false,
            "hidden": false,
            "selList": "vndrList"
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "ingrGrmsPerOz",
            "label": "Grams/Oz",
            "type": "decimal",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "ingrDesc",
            "label": "Description",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrID": "id",
      "ingrName": "name",
      "ingrCode": "code",
      "ingrDesc": "description",
      "measID": "default_measure_unit",
      "vndrID": "default_vendor",
      "ingrGrmsPerOz": "grams_per_ounce",
      "ingrTypeID": "ingredient_type_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};