// Auto-generated by genPageMaps.js
export default {
  "id": "prodBtchList",
  "title": "Product Batches",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "prodBtchList"
  },
  "uiConfig": {
    "section": "products",
    "icon": "Inventory",
    "color": "blue",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "prodBtchID",
        "label": "prodBtchID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "btchNbr",
        "label": "Batch Number",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "btchLoc",
        "label": "Location",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "btchQty",
        "label": "Quantity",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "measID",
        "label": "Measure",
        "width": "120",
        "type": "select",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodID",
        "label": "prodID",
        "width": 150,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "prodBtchID",
            "label": "prodBtchID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "btchNbr",
            "label": "Batch Number",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "comments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          },
          {
            "field": "prodID",
            "label": "prodID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "btchLoc",
            "label": "Location",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "btchQty",
            "label": "Quantity",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "measID",
            "label": "Measure",
            "type": "select",
            "required": true,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "prodBtchID": "prodBtchID",
      "btchNbr": "btchNbr",
      "btchLoc": "btchLoc",
      "btchQty": "btchQty",
      "measID": "measID",
      "comments": "comments",
      "prodID": "prodID"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "prodBtchID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};