// Auto-generated by genPageMaps.js
export default {
  "id": "prodTypeList",
  "title": "Product Types",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "prodTypeList"
  },
  "uiConfig": {
    "section": "products",
    "icon": "Category",
    "color": "blue",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "prodTypeID",
        "label": "prodTypeID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "prodTypeName",
        "label": "Type Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "prodTypeID",
            "label": "prodTypeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "prodTypeName",
            "label": "Type Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "prodTypeID": "prodTypeID",
      "prodTypeName": "prodTypeName",
      "acctID": "acctID"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "prodTypeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};