// Auto-generated by genPageMaps.js
export default {
  "id": "userList",
  "title": "Users",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "userList"
  },
  "uiConfig": {
    "section": "admin",
    "icon": "People",
    "color": "purple",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": []
  },
  "formConfig": {
    "groups": []
  },
  "dmlConfig": {
    "fieldMappings": {},
    "operations": {
      "insert": {
        "excludeFields": []
      },
      "update": {},
      "delete": {}
    }
  }
};