// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "ingrBtchList",
  "title": "Ingredient Batches",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredient_batches",
    "primaryKey": "ingrBtchID",
    "listEvent": "ingrBtchList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "section": "INGREDIENTS",
    "layout": "CrudLayout",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        },
        {
          "id": "navigate",
          "icon": "Visibility",
          "color": "primary",
          "tooltip": "View btchMapping",
          "route": "/mapping/:prodBtchID/btchMapDetail",
          "paramField": "ingrBtchID"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": []
  },
  "formConfig": {
    "groups": []
  },
  "dmlConfig": {
    "fieldMappings": {},
    "operations": {
      "insert": {
        "excludeFields": []
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;