// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "prodTypeList",
  "title": "Product Types",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "product_types",
    "primaryKey": "prodTypeID",
    "listEvent": "prodTypeList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "category",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "prodTypeID",
        "label": "prodTypeID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "prodTypeID",
            "label": "prodTypeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "prodTypeID": "id",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "prodTypeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;