/**
 * Preview Routes Manifest
 * AUTO-GENERATED by genPageConfig - DO NOT EDIT MANUALLY
 *
 * This file is automatically updated when pages are generated via genPageConfig.
 * Preview routes allow testing database-generated pages before deployment.
 */

export const PREVIEW_ROUTES = [
  {
    "path": "/preview/monorepo/studio",
    "component": "preview/monorepo/studio",
    "title": "studio",
    "appName": "monorepo",
    "pageName": "studio",
    "generated": "2025-10-04T16:34:56.357Z"
  },
  {
    "path": "/preview/login/loginPage",
    "component": "preview/login/loginPage",
    "title": "loginPage",
    "appName": "login",
    "pageName": "loginPage",
    "generated": "2025-10-04T20:27:42.467Z"
  },
  {
    "path": "/preview/whatsfresh/ingrTypePage",
    "component": "preview/whatsfresh/ingrTypePage",
    "title": "ingrTypePage",
    "appName": "whatsfresh",
    "pageName": "ingrTypePage",
    "generated": "2025-10-06T12:19:27.402Z"
  },
  {
    "path": "/preview/whatsfresh/ingrPage",
    "component": "preview/whatsfresh/ingrPage",
    "title": "ingrPage",
    "appName": "whatsfresh",
    "pageName": "ingrPage",
    "generated": "2025-10-04T20:27:17.844Z"
  }
];
