/**
 * Generated by Babel parser
 */
import React from 'react';

import { pageSketchPad } from './page/pageSketchPad.js';

export { pageSketchPad };

export default function SketchPad() {
  return <div>SketchPad with 1 eventTypes</div>;
};
