import React, { useState, useEffect } from "react";
import DirectRenderer from '../../../rendering/DirectRenderer';
import pageConfig from "./pageConfig.json";

/**
 * loginPage - Database-generated page
 * Auto-generated by genPageConfig from database eventTypes
 */
const loginPage = () => {
  const [config, setConfig] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setConfig(pageConfig);
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        fontSize: "18px",
        color: "#666"
      }}>
        Loading loginPage...
      </div>
    );
  }

  return <DirectRenderer config={config} />;
};

export default loginPage;
