// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "prodList",
  "title": "Products",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "products",
    "primaryKey": "prodID",
    "listEvent": "prodList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "shopping_bag",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "prodID",
        "label": "prodID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "prodDfltLoc",
        "label": "Default Location",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodDfltBestBy",
        "label": "Best By Days",
        "width": "80",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodUpcChkDgt",
        "label": "UPC Check Digit",
        "width": "80",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "prodTypeID",
        "label": "prodTypeID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "prodID",
            "label": "prodID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "prodDesc",
            "label": "Description",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "prodTypeID",
            "label": "prodTypeID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "prodDfltLoc",
            "label": "Default Location",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "prodDfltBestBy",
            "label": "Best By Days",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "prodUpcChkDgt",
            "label": "UPC Check Digit",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "prodID": "id",
      "prodDfltLoc": "location",
      "prodDfltBestBy": "best_by_days",
      "prodDesc": "description",
      "prodUpcChkDgt": "upc_check_digit",
      "prodTypeID": "product_type_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "prodID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;