/**
 * Generated Navigation Configuration for admin
 * Auto-generated by devtools - DO NOT EDIT MANUALLY
 */

import { getNavSections } from './routes.js';

/**
 * Navigation configuration for the application sidebar
 * Based on the section structure defined in routes.js
 */
export const navigationConfig = (acctID) => {
  // Get sections with their items from routes
  const sections = getNavSections();
  const result = [];
  
  sections.forEach(section => {
    const sectionConfig = {
      name: section.name,
      items: section.items.map(item => ({
        name: item.title,
        icon: item.icon,
        route: item.routeKey,
        color: item.color || 'gray'
      }))
    };
    
    result.push(sectionConfig);
  });
  
  return result;
};

// Generated on: 2025-07-04T19:37:30.072Z
