/**
 * Generated Routes Configuration for admin
 * Auto-generated by devtools - DO NOT EDIT MANUALLY
 */

export const ROUTES = {
  "ADMIN_ACCOUNTS": {
    "path": "/acctList",
    "component": "01-acctList/index.jsx",
    "layout": "CrudLayout",
    "title": "Accounts",
    "icon": "AccountBox",
    "section": "admin",
    "eventType": "acctList",
    "params": [],
    "category": "page:Crud"
  },
  "ADMIN_USERS": {
    "path": "/userList",
    "component": "02-userList/index.jsx",
    "layout": "CrudLayout",
    "title": "Users",
    "icon": "Group",
    "section": "admin",
    "eventType": "userList",
    "params": [
      ":acctID"
    ],
    "category": "page:Crud"
  }
};

export const SECTIONS = {
  "admin": {
    "name": "admin",
    "order": 1,
    "items": [
      {
        "routeKey": "ADMIN_ACCOUNTS",
        "title": "Accounts",
        "icon": "AccountBox",
        "order": 1,
        "color": "indigo"
      },
      {
        "routeKey": "ADMIN_USERS",
        "title": "Users",
        "icon": "Group",
        "order": 2,
        "color": "indigo"
      }
    ]
  }
};

export function getNavSections() {
  return Object.values(SECTIONS).sort((a, b) => (a.order || 999) - (b.order || 999));
}

export function getRoute(routeKey) {
  return ROUTES[routeKey];
}

export function resolveRoute(eventType) {
  return Object.values(ROUTES).find(route => route.eventType === eventType);
}

// Generated on: 2025-07-04T19:37:30.072Z
