// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "brndList",
  "title": "Brands",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "brands",
    "primaryKey": "brndID",
    "listEvent": "brndList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "branding_watermark",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "brndID",
        "label": "brndID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "brndID",
            "label": "brndID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "brndURL",
            "label": "Website",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "brndComments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "brndID": "id",
      "brndComments": "comments",
      "brndURL": "url",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "brndID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;