capability: component-cloning
description: Duplicate template components for new pages
compatible_agents:  [vscode-copilot, claude, github-copilot]
estimated_tokens: 3000-5000

patterns:
  crud_template_clone:
    description: Clone CRUD Grid + Form components
    reference_page_id: 11  # Event Types template
    query_template: |
      SELECT * FROM api_wf.eventComp_xref 
      WHERE page_id = 11 
      ORDER BY sequence;
    clone_steps:
      1:  "Query template components"
      2: "For each target page, duplicate all components"
      3: "Update page_id, eventType_id"
      4: "Update component labels/titles"
      5: "Maintain sequence order"
    expected_count: "~9 components per page"
  batch_clone:
    description: Clone for multiple pages at once
    strategy: "Use transaction for atomicity"
    batch_size: 50  # SQL INSERT batch size

impact_logging:
  procedure: sp_logPlanImpact
  target_table: api_wf.eventComp_xref
  description_template: "Cloned CRUD components for {count} pages ({total_rows} entries)"

agent_selection:
  prefer:  vscode-copilot
  fallback: [claude, github-copilot]
  criteria:
    - "Use vscode-copilot if in IDE context"
    - "Use claude for large batch operations"
    - "Consider token limits for batch size"
