// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "ingrList",
  "title": "Ingredients",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredients",
    "primaryKey": "ingrID",
    "listEvent": "ingrList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "grass",
    "actions": {
      "rowActions": [
        {
          "id": "delete",
          "icon": "Delete",
          "color": "error",
          "tooltip": "Delete",
          "handler": "handleDelete"
        }
      ],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrID",
        "label": "ingrID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrGrmsPerOz",
        "label": "Grams/Oz",
        "width": "100",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrTypeID",
        "label": "ingrTypeID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrID",
            "label": "ingrID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrTypeID",
            "label": "ingrTypeID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "measID",
            "label": "Default Measure",
            "type": "select",
            "required": false,
            "hidden": false,
            "widget": "SelMeas"
          },
          {
            "field": "vndrID",
            "label": "Default Vendor",
            "type": "select",
            "required": false,
            "hidden": false,
            "widget": "SelVndr"
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "ingrGrmsPerOz",
            "label": "Grams/Oz",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "ingrDesc",
            "label": "Description",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrID": "id",
      "ingrDesc": "description",
      "measID": "default_measure_unit",
      "vndrID": "default_vendor",
      "ingrGrmsPerOz": "grams_per_ounce",
      "ingrTypeID": "ingredient_type_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;