/**
 * Analysis Document Template
 * Generates formatted analysis documents
 */

/**
 * Generate analysis document content
 * @param {Object} params - Template parameters
 * @returns {string} Formatted analysis document
 */
export function analysisTemplate(params) {
  const {
    planId,
    docID,
    topic,
    content,
    agent = "Claude",
    ...options
  } = params;
  const currentDate = new Date().toISOString().split("T")[0];

  return `# ${agent} Analysis: ${topic}
**DocID**: ${
    docID || planId
  } | **Created**: ${currentDate} | **Agent**: ${agent}

## Analysis Summary
${content}

## Architectural Considerations
${
  options.architecturalNotes ||
  "[Architectural considerations to be documented]"
}

## Implementation Risks
${options.risks || "[Implementation risks to be assessed]"}

## Integration Points
${options.integrationPoints || "[Integration points to be identified]"}

## Recommendations
${options.recommendations || "[Recommendations to be provided]"}

---
*This analysis was generated by ${agent} to support Plan ${planId} implementation.*`;
}

export default analysisTemplate;
