import React, { Suspense, lazy, useEffect } from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import SimpleLayout from "./layouts/SimpleLayout.jsx";
import { getNavigationSections, getAppBarConfig } from "./config/navigation.js";
import { ROUTES } from "./config/routes.js";
import { loadMermaidLibrary } from "./utils/mermaidLoader.js";

// Load preview routes (auto-generated by genPageConfig)
let PREVIEW_ROUTES = [];
try {
  const previewModule = await import("./config/preview-routes.js");
  PREVIEW_ROUTES = previewModule.PREVIEW_ROUTES || [];
} catch (error) {
  console.warn('⚠️ No preview routes found - preview-routes.js not generated yet');
}

// Import Studio page directly for full-screen rendering
const StudioPage = lazy(() => import("./pages/Studio/index.jsx"));

const App = () => {
  // App startup initialization
  useEffect(() => {
    // Load mermaid.js globally for Studio
    loadMermaidLibrary().catch(console.error);
    console.log('✅ Studio App: Startup complete');

    // Register global selectEventTypeTab function for mermaid
    window.selectEventTypeTab = (nodeId) => {
      console.log(`🎯 App: selectEventTypeTab called with: ${nodeId}`);
      // We'll need to access workflowEngine here
      console.log('🔧 selectEventTypeTab function registered globally');
    };
  }, []);

  // Studio-specific route generation
  const generateRoutes = () => {
    return Object.entries(ROUTES).map(([routeKey, route]) => {
      // Lazy load each page component
      const PageComponent = lazy(() => import(`./pages/${route.component}`));

      return (
        <Route
          key={routeKey}
          path={route.path}
          element={
            <Suspense fallback={<div>Loading {route.title || route.component}...</div>}>
              <PageComponent
                mode="studio"
              />
            </Suspense>
          }
        />
      );
    });
  };

  // Generate preview routes dynamically
  const generatePreviewRoutes = () => {
    return PREVIEW_ROUTES.map((route) => {
      const PreviewComponent = lazy(() => import(`./${route.component}`));

      return (
        <Route
          key={route.path}
          path={route.path}
          element={
            <Suspense fallback={<div>Loading Preview: {route.title}...</div>}>
              <PreviewComponent />
            </Suspense>
          }
        />
      );
    });
  };

  return (
    <Router>
      <Routes>
        {/* Studio route - full screen, no SimpleLayout */}
        <Route
          path="/studio"
          element={
            <Suspense fallback={<div>Loading Studio...</div>}>
              <StudioPage mode="studio" />
            </Suspense>
          }
        />

        {/* Login route - test database-driven rendering */}
        <Route
          path="/login"
          element={
            <Suspense fallback={<div>Loading Login...</div>}>
              <div style={{ padding: "20px" }}>
                {React.createElement(lazy(() => import("./pages/Login/index.jsx")))}
              </div>
            </Suspense>
          }
        />

        {/* Preview routes - database-generated pages (no layout) */}
        {generatePreviewRoutes()}

        {/* All other routes use SimpleLayout */}
        <Route
          path="/*"
          element={
            <SimpleLayout
              navigationSections={getNavigationSections()}
              appBarConfig={getAppBarConfig()}
              appName="WhatsFresh Studio"
              onLogout={() => {
                console.log("Studio logout clicked");
              }}
            >
              <Routes>
                {/* Default route */}
                <Route
                  path="/"
                  element={
                    <div style={{ padding: "20px" }}>
                      <h1>WhatsFresh Studio</h1>
                      <p>Visual EventType Design & Development Environment</p>
                      <p>Navigate to Studio to start designing your eventTypes.</p>
                    </div>
                  }
                />
              </Routes>
            </SimpleLayout>
          }
        />
      </Routes>
    </Router>
  );
};

export default App;