graph TD

    ingrTypePage["ingrTypePage<br/>ctgry: [page]"]
    crudContainer["crudContainer<br/>ctgry: [container]"]
    ingrTypePage --> crudContainer
    ingrTypeGrid["ingrTypeGrid<br/>ctgry: [grid]"]
    crudContainer --> ingrTypeGrid
    ingrTypeForm["ingrTypeForm<br/>ctgry: [form]"]
    crudContainer --> ingrTypeForm

    %% Click handlers for Studio integration
    click ingrTypePage href "javascript:window.selectEventTypeTab(57)"
    click crudContainer href "javascript:window.selectEventTypeTab(60)"
    click ingrTypeGrid href "javascript:window.selectEventTypeTab(56)"
    click ingrTypeForm href "javascript:window.selectEventTypeTab(59)"