CREATE
OR REPLACE VIEW vw_sprint_outline AS with sprint_data as (select p.id AS id,
p.name AS name,
p.agile AS agile,
p.status AS status,
p.priority AS priority,
p.parentID AS parentID,
p.sprint_order AS sprint_order,
p.created_at AS created_at,
p.updated_at AS updated_at,
(case when (p.agile = 'epic') then p.id else p.parentID end) AS epic_id,
(case when (p.agile = 'epic') then 0 else 1 end) AS is_sprint
FROM plans p
WHERE ((p.active = 1)
AND (p.deleted_at is null))),
epic_stats as (select sprint_data.epic_id AS epic_id,
count(0) AS total_sprints,
sum((case when (sprint_data.status = 'complete') then 1 else 0 end)) AS completed_sprints,
sum((case when (sprint_data.status = 'current') then 1 else 0 end)) AS active_sprints from sprint_data where (sprint_data.is_sprint = 1)
GROUP BY sprint_data.epic_id) select s.id AS id,
s.name AS name,
s.agile AS agile,
s.status AS status,
s.priority AS priority,
s.parentID AS parentID,
s.sprint_order AS sprint_order,
s.epic_id AS epic_id,
s.is_sprint AS is_sprint,
s.created_at AS created_at,
s.updated_at AS updated_at,
coalesce(es.total_sprints,
0) AS total_sprints,
coalesce(es.completed_sprints,
0) AS completed_sprints,
coalesce(es.active_sprints,
0) AS active_sprints,
(case when (s.is_sprint = 1) then concat('  ├── Sprint ',
s.id,
': ',
s.name,
' - ',
upper(s.status),
' - ',
upper(s.priority)) else concat('Plan ',
s.id,
': ',
s.name,
' - ',
upper(s.status),
' - ',
upper(s.priority),
(case when (es.total_sprints > 0) then concat(' (',
es.completed_sprints,
'/',
es.total_sprints,
' sprints complete)') else '' end)) end) AS formatted_line,
(case when (s.is_sprint = 1) then s.parentID else s.id end) AS sort_epic,
s.is_sprint AS sort_level,
s.sprint_order AS sort_order from (sprint_data s
LEFT JOIN epic_stats es on(((s.epic_id = es.epic_id)
AND (s.is_sprint = 0))))
ORDER BY (case when (s.is_sprint = 1) then s.parentID else s.id end),
s.is_sprint,
s.sprint_order;
