CREATE
    OR REPLACE VIEW `wf_ingrBtchDtl` AS
  SELECT
    `it`.`name` AS `ingrTypeName`,`i`.`name` AS `ingrName`,`i`.`code` AS `ingrCode`,ifnull(`ib`.`batch_number`,'No Batches') AS `ingrBtchNbr`,`i`.`grams_per_ounce` AS `gmsPerOz`,`i`.`description` AS `ingrDesc`,`i`.`default_measure_unit` AS `dfltMeasId`,`i`.`default_vendor` AS `dfltVndrId`,ifnull(`ib`.`lot_number`,'') AS `ingrLotNbr`,(ifnull(date_format(`ib`.`purchase_date`,'%Y-%m-%d'),'') collate utf8mb4_unicode_ci) AS `purchDate`,ifnull(`ib`.`purchase_quantity`,'') AS `purchQty`,`whatsfresh`.`f_measure`(`ib`.`measure_id`) AS `purchMeas`,`ib`.`unit_quantity` AS `unitQty`,`ib`.`unit_price` AS `unitPrice`,cast((ifnull(`ib`.`unit_price`,0) / ifnull(`ib`.`unit_quantity`,1)) as decimal(9,4)) AS `unitRate`,ifnull(concat(`ib`.`purchase_quantity`,' @ ',concat('$',format(ifnull(`ib`.`unit_price`,0),2)),' per ',(trim(round(`ib`.`unit_quantity`,2)) + 0),' ',`whatsfresh`.`f_measure`(`ib`.`measure_id`)),'') AS `purchDtl`,concat('$',format(ifnull((`ib`.`purchase_quantity` * `ib`.`unit_price`),0),2)) AS `purchAmt`,ifnull((`ib`.`purchase_quantity` * `ib`.`unit_price`),0) AS `purchTotalAmt`,`whatsfresh`.`f_vendor`(`ib`.`vendor_id`) AS `vndrName`,`whatsfresh`.`f_brand`(`ib`.`brand_id`) AS `brndName`,ifnull(date_format(`ib`.`best_by_date`,'%Y-%m-%d'),'') AS `bestByDate`,ifnull(`pbi`.`prd_btch_cnt`,0) AS `prdBtchCnt`,`ib`.`comments` AS `comments`,concat(`ib`.`purchase_date`,' : ',`whatsfresh`.`f_vendor`(`ib`.`vendor_id`)) AS `shopEvent`,`i`.`active` AS `ingrActv`,`ib`.`active` AS `ingrBtchActv`,`it`.`active` AS `ingrTypeActv`,`i`.`account_id` AS `account_id`,`ib`.`id` AS `ingredient_batch_id`,`i`.`id` AS `ingredient_id`,`it`.`id` AS `ingredient_type_id`,`ib`.`vendor_id` AS `vendor_id`,`ib`.`brand_id` AS `brand_id`,cast(`ib`.`measure_id` as signed) AS `measure_id`,`ib`.`shop_event_id` AS `shop_event_id`
  FROM (((`whatsfresh`.`ingredients` `i`
    LEFT JOIN (select `a`.`id` AS `id`,`a`.`ingredient_id` AS `ingredient_id`,`a`.`shop_event_id` AS `shop_event_id`,`a`.`vendor_id` AS `vendor_id`,`a`.`brand_id` AS `brand_id`,`a`.`lot_number` AS `lot_number`,`a`.`batch_number` AS `batch_number`,`a`.`purchase_date` AS `purchase_date`,`a`.`purchase_quantity` AS `purchase_quantity`,`a`.`global_measure_unit_id` AS `global_measure_unit_id`,`a`.`measure_id` AS `measure_id`,`a`.`unit_quantity` AS `unit_quantity`,`a`.`unit_price` AS `unit_price`,`a`.`purchase_total_amount` AS `purchase_total_amount`,`a`.`best_by_date` AS `best_by_date`,`a`.`comments` AS `comments`,`a`.`created_at` AS `created_at`,`a`.`created_by` AS `created_by`,`a`.`updated_at` AS `updated_at`,`a`.`updated_by` AS `updated_by`,`a`.`deleted_at` AS `deleted_at`,`a`.`deleted_by` AS `deleted_by`,`a`.`oldUUID` AS `oldUUID`,`a`.`active` AS `active` from `whatsfresh`.`ingredient_batches` `a`
  WHERE (year(`a`.`purchase_date`) >= year((now() - interval 7 year)))) `ib` on((`i`.`id` = `ib`.`ingredient_id`)))
    LEFT JOIN `whatsfresh`.`ingredient_types` `it` on((`i`.`ingredient_type_id` = `it`.`id`)))
    LEFT JOIN (select `whatsfresh`.`product_batch_ingredients`.`ingredient_batch_id` AS `ingredient_batch_id`,count(0) AS `prd_btch_cnt` from `whatsfresh`.`product_batch_ingredients`
  GROUP BY `whatsfresh`.`product_batch_ingredients`.`ingredient_batch_id`) `pbi` on((`ib`.`id` = `pbi`.`ingredient_batch_id`)));
