/**
 * Generated by Babel parser
 */
import React from 'react';

import { pageDashboard } from './page/pageDashboard.js';

export { pageDashboard };

export default function Dashboard() {
  return <div>Dashboard with 1 eventTypes</div>;
};
