import React from 'react';
import AuthLayout from '../../layouts/AuthLayout';
import pageMap from './pageMap';


/**
 * userLogin Page
 * Generated by DevTools - Simple wrapper around AuthLayout
 * All data fetching, state management, and UI handled internally by AuthLayout
 */
const userLogin = () => {
  return <AuthLayout pageMap={pageMap} />;
};

export default userLogin;
