export default {
  "id": "acctList",
  "title": "Accounts",
  "schema": "whatsfresh",
  "table": "accounts",
  "section": "admin",
  "icon": "AccountBox",
  "color": "purple",
  "keyField": "acctID",
  "columns": {
    "acctID": {
      "id": 1,
      "field": "acctID",
      "db_column": "id",
      "headerName": "ID",
      "width": 150,
      "type": "number",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "acctName": {
      "id": 2,
      "field": "acctName",
      "db_column": "name",
      "headerName": "Account Name",
      "width": 200,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": true,
      "primaryKey": false,
      "editable": true,
      "searchable": true
    },
    "acctDesc": {
      "id": 3,
      "field": "acctDesc",
      "db_column": "description",
      "headerName": "Description",
      "width": 150,
      "type": "multiline",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctAddr": {
      "id": 4,
      "field": "acctAddr",
      "db_column": "street_address",
      "headerName": "Address",
      "width": 200,
      "type": "text",
      "group": 2,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctCity": {
      "id": 5,
      "field": "acctCity",
      "db_column": "city",
      "headerName": "City",
      "width": 150,
      "type": "text",
      "group": 3,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctState": {
      "id": 6,
      "field": "acctState",
      "db_column": "state_code",
      "headerName": "State",
      "width": 60,
      "type": "text",
      "group": 3,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctZipCode": {
      "id": 7,
      "field": "acctZipCode",
      "db_column": "zip_code",
      "headerName": "ZIP",
      "width": 80,
      "type": "text",
      "group": 3,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctCompCode": {
      "id": 8,
      "field": "acctCompCode",
      "db_column": "company_code",
      "headerName": "Company Code",
      "width": 120,
      "type": "text",
      "group": 4,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctDfltLoc": {
      "id": 9,
      "field": "acctDfltLoc",
      "db_column": "default_location",
      "headerName": "Default Location",
      "width": 150,
      "type": "text",
      "group": 4,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctURL": {
      "id": 10,
      "field": "acctURL",
      "db_column": "url",
      "headerName": "Website URL",
      "width": 200,
      "type": "text",
      "group": 5,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctPayCustCode": {
      "id": 11,
      "field": "acctPayCustCode",
      "db_column": "payment_customer_code",
      "headerName": "Customer Code",
      "width": 150,
      "type": "text",
      "group": 6,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctSubsptnCode": {
      "id": 12,
      "field": "acctSubsptnCode",
      "db_column": "payment_subscription_code",
      "headerName": "Subscription Code",
      "width": 150,
      "type": "text",
      "group": 6,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    }
  }
};