// Auto-generated by genPageMaps.js
export default {
  "id": "ingrBtchList",
  "title": "Ingredient Batches",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredient_batches",
    "primaryKey": "ingrBtchID",
    "parentIdField": "ingrID",
    "listEvent": "ingrBtchList"
  },
  "uiConfig": {
    "section": "ingredients",
    "icon": "Inventory",
    "color": "pink",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "btchID",
        "label": "btchID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "btchNbr",
        "label": "Batch Number",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "unitQty",
        "label": "Unit Qty",
        "width": "80",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "unitPrice",
        "label": "Unit Price",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "purchQty",
        "label": "Purchase Qty",
        "width": "100",
        "type": "decimal",
        "editable": true,
        "hidden": false
      },
      {
        "field": "lotNbr",
        "label": "Lot Number",
        "width": "150",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "ingrID",
        "label": "ingrID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "btchID",
            "label": "btchID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "btchNbr",
            "label": "Batch Number",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "vndrID",
            "label": "Vendor",
            "type": "select",
            "required": true,
            "hidden": false,
            "selList": "vndrList"
          },
          {
            "field": "comments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          },
          {
            "field": "ingrID",
            "label": "ingrID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "brndID",
            "label": "Brand",
            "type": "select",
            "required": false,
            "hidden": false,
            "selList": "brndList"
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "unitQty",
            "label": "Unit Qty",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "unitPrice",
            "label": "Unit Price",
            "type": "decimal",
            "required": false,
            "hidden": false
          },
          {
            "field": "purchQty",
            "label": "Purchase Qty",
            "type": "decimal",
            "required": true,
            "hidden": false
          },
          {
            "field": "measID",
            "label": "Measure",
            "type": "select",
            "required": true,
            "hidden": false,
            "selList": "measList"
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "lotNbr",
            "label": "Lot Number",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "btchID": "id",
      "btchNbr": "batch_number",
      "vndrID": "vendor_id",
      "brndID": "brand_id",
      "unitQty": "unit_quantity",
      "unitPrice": "unit_price",
      "purchQty": "purchase_quantity",
      "measID": "global_measure_unit_id",
      "lotNbr": "lot_number",
      "comments": "comments",
      "ingrID": "ingredient_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "btchID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};