// Auto-generated by genPageMaps.js
export default {
  "id": "ingrTypeList",
  "title": "Ingredient Types",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "ingredient_types",
    "primaryKey": "ingrTypeID",
    "parentIdField": "acctID",
    "childEntity": "ingrList",
    "childIdField": "ingrTypeID",
    "listEvent": "ingrTypeList"
  },
  "uiConfig": {
    "section": "ingredients",
    "icon": "Category",
    "color": "pink",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "ingrTypeID",
        "label": "ingrTypeID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "ingrTypeName",
        "label": "Type Name",
        "width": "200",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 150,
        "type": "text",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "ingrTypeID",
            "label": "ingrTypeID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "ingrTypeName",
            "label": "Type Name",
            "type": "text",
            "required": true,
            "hidden": false
          },
          {
            "field": "ingrTypeDesc",
            "label": "Description",
            "type": "multiLine",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "text",
            "required": false,
            "hidden": true
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "ingrTypeID": "id",
      "ingrTypeName": "name",
      "ingrTypeDesc": "description",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "ingrTypeID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};