export default {
  "id": "ingrBtchList",
  "title": "Ingredient Batches",
  "schema": "whatsfresh",
  "table": "ingredient_batches",
  "section": "ingredients",
  "icon": "Inventory",
  "color": "pink",
  "parentIdField": "ingrID",
  "keyField": "ingrBtchID",
  "actions": {
    "rowActions": [],
    "tableActions": []
  },
  "columns": {
    "btchID": {
      "id": 1,
      "field": "btchID",
      "db_column": "id",
      "headerName": "ID",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "btchNbr": {
      "id": 2,
      "field": "btchNbr",
      "db_column": "batch_number",
      "headerName": "Batch Number",
      "width": 120,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": true,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "vndrID": {
      "id": 3,
      "field": "vndrID",
      "db_column": "vendor_id",
      "headerName": "Vendor",
      "width": 180,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "brndID": {
      "id": 4,
      "field": "brndID",
      "db_column": "brand_id",
      "headerName": "Brand",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "unitQty": {
      "id": 5,
      "field": "unitQty",
      "db_column": "unit_quantity",
      "headerName": "Unit Qty",
      "width": 80,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "unitPrice": {
      "id": 6,
      "field": "unitPrice",
      "db_column": "unit_price",
      "headerName": "Unit Price",
      "width": 100,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "purchQty": {
      "id": 7,
      "field": "purchQty",
      "db_column": "purchase_quantity",
      "headerName": "Purchase Qty",
      "width": 100,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "measID": {
      "id": 8,
      "field": "measID",
      "db_column": "global_measure_unit_id",
      "headerName": "Measure",
      "width": 120,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "lotNbr": {
      "id": 9,
      "field": "lotNbr",
      "db_column": "lot_number",
      "headerName": "Lot Number",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "comments": {
      "id": 10,
      "field": "comments",
      "db_column": "comments",
      "headerName": "Comments",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "ingrID": {
      "id": 11,
      "field": "ingrID",
      "db_column": "ingredient_id",
      "headerName": "ID",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": false,
      "searchable": false
    }
  }
};