export default {
  "id": "ingrList",
  "title": "Ingredients",
  "schema": "whatsfresh",
  "table": "ingredients",
  "section": "ingredients",
  "icon": "ListAlt",
  "color": "pink",
  "parentIdField": "ingrTypeID",
  "childEntity": "ingrBtchList",
  "childIdField": "ingrID",
  "keyField": "ingrID",
  "columns": {
    "ingrID": {
      "id": 1,
      "field": "ingrID",
      "db_column": "id",
      "headerName": "ID",
      "width": 150,
      "type": "number",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "ingrName": {
      "id": 2,
      "field": "ingrName",
      "db_column": "name",
      "headerName": "Ingredient Name",
      "width": 200,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": true,
      "primaryKey": false,
      "editable": true,
      "searchable": true
    },
    "ingrCode": {
      "id": 3,
      "field": "ingrCode",
      "db_column": "code",
      "headerName": "Code",
      "width": 100,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "ingrDesc": {
      "id": 4,
      "field": "ingrDesc",
      "db_column": "description",
      "headerName": "Description",
      "width": 150,
      "type": "multiline",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "measID": {
      "id": 5,
      "field": "measID",
      "db_column": "default_measure_unit",
      "headerName": "Default Measure",
      "width": 120,
      "type": "select",
      "group": 2,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false,
      "entity": "measList",
      "valueField": "measID",
      "displayField": "name"
    },
    "vndrID": {
      "id": 6,
      "field": "vndrID",
      "db_column": "default_vendor",
      "headerName": "Default Vendor",
      "width": 150,
      "type": "select",
      "group": 2,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false,
      "entity": "vndrList",
      "valueField": "vndrID",
      "displayField": "vndrName"
    },
    "ingrGrmsPerOz": {
      "id": 7,
      "field": "ingrGrmsPerOz",
      "db_column": "grams_per_ounce",
      "headerName": "Grams/Oz",
      "width": 100,
      "type": "decimal",
      "group": 3,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "ingrTypeID": {
      "id": 8,
      "field": "ingrTypeID",
      "db_column": "ingredient_type_id",
      "headerName": "Type I D",
      "width": 150,
      "type": "select",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": false,
      "searchable": false,
      "entity": "ingrTypeList",
      "valueField": "ingrTypeID",
      "displayField": "ingrTypeName"
    }
  }
};