export default {
  "id": "prodList",
  "title": "Products",
  "schema": "whatsfresh",
  "table": "products",
  "section": "products",
  "icon": "Fastfood",
  "color": "blue",
  "parentIdField": "prodTypeID",
  "childEntity": "prodBtchList",
  "childIdField": "prodID",
  "keyField": "prodID",
  "actions": {
    "rowActions": [],
    "tableActions": []
  },
  "columns": {
    "prodID": {
      "id": 1,
      "field": "prodID",
      "db_column": "id",
      "headerName": "ID",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "prodName": {
      "id": 2,
      "field": "prodName",
      "db_column": "name",
      "headerName": "Product Name",
      "width": 200,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": true,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodCode": {
      "id": 3,
      "field": "prodCode",
      "db_column": "code",
      "headerName": "Code",
      "width": 100,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodDfltLoc": {
      "id": 4,
      "field": "prodDfltLoc",
      "db_column": "location",
      "headerName": "Default Location",
      "width": 120,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodDfltBestBy": {
      "id": 5,
      "field": "prodDfltBestBy",
      "db_column": "best_by_days",
      "headerName": "Best By Days",
      "width": 80,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodDesc": {
      "id": 6,
      "field": "prodDesc",
      "db_column": "description",
      "headerName": "Description",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodUpcItemRef": {
      "id": 7,
      "field": "prodUpcItemRef",
      "db_column": "upc_item_reference",
      "headerName": "UPC Reference",
      "width": 120,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodUpcChkDgt": {
      "id": 8,
      "field": "prodUpcChkDgt",
      "db_column": "upc_check_digit",
      "headerName": "UPC Check Digit",
      "width": 80,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodTypeID": {
      "id": 9,
      "field": "prodTypeID",
      "db_column": "product_type_id",
      "headerName": "Type I D",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": false,
      "searchable": false
    }
  }
};