export default {
  "id": "rcpeList",
  "title": "Product Recipes",
  "schema": "whatsfresh",
  "table": "product_recipes",
  "section": "maps",
  "icon": "MenuBook",
  "color": "green",
  "parentIdField": "prodID",
  "keyField": "rcpeID",
  "actions": {
    "rowActions": [],
    "tableActions": []
  },
  "columns": {
    "rcpeID": {
      "id": 1,
      "field": "rcpeID",
      "db_column": "prd_rcpe_id",
      "headerName": "ID",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "ingrOrdr": {
      "id": 2,
      "field": "ingrOrdr",
      "db_column": "ingr_ordr",
      "headerName": "Order",
      "width": 80,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "ingrName": {
      "id": 3,
      "field": "ingrName",
      "db_column": "ingr_name",
      "headerName": "Ingredient Name",
      "width": 200,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "qtyMeas": {
      "id": 4,
      "field": "qtyMeas",
      "db_column": "ingr_qty_meas",
      "headerName": "Quantity & Measure",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "prodID": {
      "id": 5,
      "field": "prodID",
      "db_column": "prd_id",
      "headerName": "ID",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": false,
      "searchable": false
    },
    "ingrTypeSel": {
      "id": 6,
      "field": "ingrTypeSel",
      "db_column": "ingr_type_id",
      "headerName": "Ingredient Type",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "ingrSel": {
      "id": 7,
      "field": "ingrSel",
      "db_column": "ingr_id",
      "headerName": "Ingredient",
      "width": 180,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "measID": {
      "id": 8,
      "field": "measID",
      "db_column": "ingr_meas_id",
      "headerName": "Measure",
      "width": 120,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "Qty": {
      "id": 9,
      "field": "Qty",
      "db_column": "ingr_qty",
      "headerName": "Quantity",
      "width": 100,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "Comments": {
      "id": 10,
      "field": "Comments",
      "db_column": "prd_ingr_desc",
      "headerName": "Comments",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    }
  }
};