export default {
  "id": "vndrList",
  "title": "Vendors",
  "schema": "whatsfresh",
  "table": "vendors",
  "section": "reference",
  "icon": "Business",
  "color": "gray",
  "parentIdField": "acctID",
  "keyField": "vndrID",
  "columns": {
    "vndrID": {
      "id": 1,
      "field": "vndrID",
      "db_column": "id",
      "headerName": "ID",
      "width": 150,
      "type": "number",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": true,
      "editable": false,
      "searchable": false
    },
    "vndrName": {
      "id": 2,
      "field": "vndrName",
      "db_column": "name",
      "headerName": "Vendor Name",
      "width": 200,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": true,
      "primaryKey": false,
      "editable": true,
      "searchable": true
    },
    "vndrContactName": {
      "id": 3,
      "field": "vndrContactName",
      "db_column": "contact_name",
      "headerName": "Contact Name",
      "width": 150,
      "type": "text",
      "group": 1,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "vndrContactPhone": {
      "id": 4,
      "field": "vndrContactPhone",
      "db_column": "contact_phone",
      "headerName": "Phone",
      "width": 120,
      "type": "text",
      "group": 2,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "vndrContactEmail": {
      "id": 5,
      "field": "vndrContactEmail",
      "db_column": "contact_email",
      "headerName": "Email",
      "width": 180,
      "type": "text",
      "group": 2,
      "hidden": false,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "vndrComments": {
      "id": 6,
      "field": "vndrComments",
      "db_column": "comments",
      "headerName": "Comments",
      "width": 150,
      "type": "multiline",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": true,
      "searchable": false
    },
    "acctID": {
      "id": 7,
      "field": "acctID",
      "db_column": "account_id",
      "headerName": "ID",
      "width": 150,
      "type": "select",
      "group": 1,
      "hidden": true,
      "required": false,
      "primaryKey": false,
      "editable": false,
      "searchable": false,
      "entity": "acctList",
      "valueField": "acctID",
      "displayField": "acctName"
    }
  }
};