// Auto-generated by genPageMaps.js
const pageMap = {
  "id": "vndrList",
  "title": "Vendors",
  "systemConfig": {
    "schema": "whatsfresh",
    "table": "vendors",
    "primaryKey": "vndrID",
    "listEvent": "vndrList",
    "dmlEvent": "execDML"
  },
  "uiConfig": {
    "icon": "business",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "vndrID",
        "label": "vndrID",
        "width": 80,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "vndrContactPhone",
        "label": "Phone",
        "width": "120",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "vndrContactEmail",
        "label": "Email",
        "width": "180",
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctID",
        "label": "acctID",
        "width": 120,
        "type": "select",
        "editable": false,
        "hidden": true
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "vndrID",
            "label": "vndrID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctID",
            "label": "acctID",
            "type": "select",
            "required": false,
            "hidden": true
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "vndrContactPhone",
            "label": "Phone",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "vndrContactEmail",
            "label": "Email",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "vndrComments",
            "label": "Comments",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "vndrID": "id",
      "vndrContactPhone": "contact_phone",
      "vndrContactEmail": "contact_email",
      "vndrComments": "comments",
      "acctID": "account_id"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "vndrID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};

export default pageMap;