export const btnCreateTemplate = {
  category: "btnCreate",
  
  // Button create contract - defines action button for creating records
  structure: {
    props: {
      label: "string",           // button text
      icon: "string",            // optional icon name
      variant: "string",         // primary, secondary, outlined
      size: "string",            // small, medium, large
      disabled: "boolean",       // button state
      onClick: "string"          // workflow trigger name
    }
  },
  
  // Button behavior - how it appears and acts
  layout: {
    type: "inline",             // fits inline with other elements
    alignment: "left"           // default alignment
  },

  // What PageRenderer expects for btnCreate category
  expectedStructure: {
    // Standard eventType fields
    id: "string",               // unique identifier
    category: "btnCreate",      // must be "btnCreate"
    title: "string",            // display title (often same as label)
    
    // Button-specific properties
    props: {
      label: "string",          // button text
      icon: "string",           // icon name
      variant: "string",        // styling variant
      size: "string",           // button size
      disabled: "boolean",      // enabled state
      onClick: "string",        // workflow to trigger
      style: "object"           // CSS styling overrides
    },
    
    // Workflow integration
    workflowTriggers: {
      onClick: "array"          // workflows to execute on click
    }
  },

  // Auto-generation + manual override pattern
  autoGenerated: {
    label: "string",            // "Create [EntityName]" from context
    icon: "string",             // "add" or "plus" by default
    onClick: "string"           // generated workflow name
  },
  
  overrides: {
    customLabel: "string",      // override auto label
    customIcon: "string",       // override auto icon
    customWorkflow: "string",   // override auto workflow
    styling: "object"           // custom button styling
  },

  // Validation rules for eventType creation
  required: ["id", "category", "props.label", "props.onClick"],
  
  validation: {
    "category": {
      type: "string",
      enum: ["btnCreate"]
    },
    "props.label": {
      type: "string",
      minLength: 1
    },
    "props.onClick": {
      type: "string",
      minLength: 1
    },
    "props.variant": {
      type: "string",
      enum: ["primary", "secondary", "outlined", "text"]
    },
    "props.size": {
      type: "string", 
      enum: ["small", "medium", "large"]
    }
  }
};