// Auto-generated by genPageMaps.js
export default {
  "id": "acctList",
  "title": "Accounts",
  "systemConfig": {
    "schema": "whatsfresh",
    "listEvent": "acctList"
  },
  "uiConfig": {
    "section": "admin",
    "icon": "AccountBox",
    "color": "indigo",
    "actions": {
      "rowActions": [],
      "tableActions": []
    }
  },
  "tableConfig": {
    "columns": [
      {
        "field": "acctID",
        "label": "acctID",
        "width": 150,
        "type": "number",
        "editable": false,
        "hidden": true
      },
      {
        "field": "acctName",
        "label": "Account Name",
        "width": 200,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctAddr",
        "label": "Address",
        "width": 200,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctCity",
        "label": "City",
        "width": 150,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctState",
        "label": "State",
        "width": 60,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctZipCode",
        "label": "ZIP",
        "width": 80,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctCompCode",
        "label": "Company Code",
        "width": 120,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctDfltLoc",
        "label": "Default Location",
        "width": 150,
        "type": "text",
        "editable": true,
        "hidden": false
      },
      {
        "field": "acctURL",
        "label": "Website URL",
        "width": 200,
        "type": "text",
        "editable": true,
        "hidden": false
      }
    ]
  },
  "formConfig": {
    "groups": [
      {
        "id": "1",
        "title": "Group 1",
        "fields": [
          {
            "field": "acctID",
            "label": "acctID",
            "type": "number",
            "required": false,
            "hidden": true
          },
          {
            "field": "acctName",
            "label": "Account Name",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctDesc",
            "label": "Description",
            "type": "multiLine",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "2",
        "title": "Group 2",
        "fields": [
          {
            "field": "acctAddr",
            "label": "Address",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "3",
        "title": "Group 3",
        "fields": [
          {
            "field": "acctCity",
            "label": "City",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctState",
            "label": "State",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctZipCode",
            "label": "ZIP",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "4",
        "title": "Group 4",
        "fields": [
          {
            "field": "acctCompCode",
            "label": "Company Code",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctDfltLoc",
            "label": "Default Location",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "5",
        "title": "Group 5",
        "fields": [
          {
            "field": "acctURL",
            "label": "Website URL",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      },
      {
        "id": "6",
        "title": "Group 6",
        "fields": [
          {
            "field": "acctPayCustCode",
            "label": "Customer Code",
            "type": "text",
            "required": false,
            "hidden": false
          },
          {
            "field": "acctSubsptnCode",
            "label": "Subscription Code",
            "type": "text",
            "required": false,
            "hidden": false
          }
        ]
      }
    ]
  },
  "dmlConfig": {
    "fieldMappings": {
      "acctID": "acctID",
      "acctName": "acctName",
      "acctDesc": "acctDesc",
      "acctAddr": "acctAddr",
      "acctCity": "acctCity",
      "acctState": "acctState",
      "acctZipCode": "acctZipCode",
      "acctCompCode": "acctCompCode",
      "acctDfltLoc": "acctDfltLoc",
      "acctURL": "acctURL",
      "acctPayCustCode": "acctPayCustCode",
      "acctSubsptnCode": "acctSubsptnCode"
    },
    "operations": {
      "insert": {
        "excludeFields": [
          "acctID"
        ]
      },
      "update": {},
      "delete": {}
    }
  }
};