/**
 * Generated by Babel parser
 */
import React from 'react';

import { pageStudio } from './page/pageStudio.js';

export { pageStudio };

export default function Studio() {
  return <div>Studio with 1 eventTypes</div>;
};
